// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"sync/atomic"

	"github.com/schjan/picolet/pkg/mqtt"
	mock "github.com/stretchr/testify/mock"
)

// NewMockMQTTClient creates a new instance of MockMQTTClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMQTTClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMQTTClient {
	mock := &MockMQTTClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMQTTClient is an autogenerated mock type for the MQTTClient type
type MockMQTTClient struct {
	mock.Mock
}

type MockMQTTClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMQTTClient) EXPECT() *MockMQTTClient_Expecter {
	return &MockMQTTClient_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockMQTTClient
func (_mock *MockMQTTClient) Close(ctx context.Context) {
	_mock.Called(ctx)
	return
}

// MockMQTTClient_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockMQTTClient_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockMQTTClient_Expecter) Close(ctx interface{}) *MockMQTTClient_Close_Call {
	return &MockMQTTClient_Close_Call{Call: _e.mock.On("Close", ctx)}
}

func (_c *MockMQTTClient_Close_Call) Run(run func(ctx context.Context)) *MockMQTTClient_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMQTTClient_Close_Call) Return() *MockMQTTClient_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockMQTTClient_Close_Call) RunAndReturn(run func(ctx context.Context)) *MockMQTTClient_Close_Call {
	_c.Run(run)
	return _c
}

// PublishStatus provides a mock function for the type MockMQTTClient
func (_mock *MockMQTTClient) PublishStatus(ctx context.Context, status mqtt.Status) error {
	ret := _mock.Called(ctx, status)

	if len(ret) == 0 {
		panic("no return value specified for PublishStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, mqtt.Status) error); ok {
		r0 = returnFunc(ctx, status)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMQTTClient_PublishStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishStatus'
type MockMQTTClient_PublishStatus_Call struct {
	*mock.Call
}

// PublishStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - status mqtt.Status
func (_e *MockMQTTClient_Expecter) PublishStatus(ctx interface{}, status interface{}) *MockMQTTClient_PublishStatus_Call {
	return &MockMQTTClient_PublishStatus_Call{Call: _e.mock.On("PublishStatus", ctx, status)}
}

func (_c *MockMQTTClient_PublishStatus_Call) Run(run func(ctx context.Context, status mqtt.Status)) *MockMQTTClient_PublishStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 mqtt.Status
		if args[1] != nil {
			arg1 = args[1].(mqtt.Status)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMQTTClient_PublishStatus_Call) Return(err error) *MockMQTTClient_PublishStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMQTTClient_PublishStatus_Call) RunAndReturn(run func(ctx context.Context, status mqtt.Status) error) *MockMQTTClient_PublishStatus_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function for the type MockMQTTClient
func (_mock *MockMQTTClient) Start(ctx context.Context, pauseFlag *atomic.Bool, triggerFn func()) error {
	ret := _mock.Called(ctx, pauseFlag, triggerFn)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *atomic.Bool, func()) error); ok {
		r0 = returnFunc(ctx, pauseFlag, triggerFn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMQTTClient_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockMQTTClient_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
//   - pauseFlag *atomic.Bool
//   - triggerFn func()
func (_e *MockMQTTClient_Expecter) Start(ctx interface{}, pauseFlag interface{}, triggerFn interface{}) *MockMQTTClient_Start_Call {
	return &MockMQTTClient_Start_Call{Call: _e.mock.On("Start", ctx, pauseFlag, triggerFn)}
}

func (_c *MockMQTTClient_Start_Call) Run(run func(ctx context.Context, pauseFlag *atomic.Bool, triggerFn func())) *MockMQTTClient_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *atomic.Bool
		if args[1] != nil {
			arg1 = args[1].(*atomic.Bool)
		}
		var arg2 func()
		if args[2] != nil {
			arg2 = args[2].(func())
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMQTTClient_Start_Call) Return(err error) *MockMQTTClient_Start_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMQTTClient_Start_Call) RunAndReturn(run func(ctx context.Context, pauseFlag *atomic.Bool, triggerFn func()) error) *MockMQTTClient_Start_Call {
	_c.Call.Return(run)
	return _c
}
