// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"sync/atomic"

	"github.com/schjan/picolet/pkg/mqtt"
	mock "github.com/stretchr/testify/mock"
)

// NewMockMQTTClient creates a new instance of MockMQTTClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMQTTClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMQTTClient {
	mock := &MockMQTTClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMQTTClient is an autogenerated mock type for the MQTTClient type
type MockMQTTClient struct {
	mock.Mock
}

type MockMQTTClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMQTTClient) EXPECT() *MockMQTTClient_Expecter {
	return &MockMQTTClient_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockMQTTClient
func (_mock *MockMQTTClient) Close(ctx context.Context) {
	_mock.Called(ctx)
	return
}

// MockMQTTClient_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockMQTTClient_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockMQTTClient_Expecter) Close(ctx interface{}) *MockMQTTClient_Close_Call {
	return &MockMQTTClient_Close_Call{Call: _e.mock.On("Close", ctx)}
}

func (_c *MockMQTTClient_Close_Call) Run(run func(ctx context.Context)) *MockMQTTClient_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMQTTClient_Close_Call) Return() *MockMQTTClient_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockMQTTClient_Close_Call) RunAndReturn(run func(ctx context.Context)) *MockMQTTClient_Close_Call {
	_c.Run(run)
	return _c
}

// PublishStatus provides a mock function for the type MockMQTTClient
func (_mock *MockMQTTClient) PublishStatus(ctx context.Context, status mqtt.Status) error {
	ret := _mock.Called(ctx, status)

	if len(ret) == 0 {
		panic("no return value specified for PublishStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, mqtt.Status) error); ok {
		r0 = returnFunc(ctx, status)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMQTTClient_PublishStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishStatus'
type MockMQTTClient_PublishStatus_Call struct {
	*mock.Call
}

// PublishStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - status mqtt.Status
func (_e *MockMQTTClient_Expecter) PublishStatus(ctx interface{}, status interface{}) *MockMQTTClient_PublishStatus_Call {
	return &MockMQTTClient_PublishStatus_Call{Call: _e.mock.On("PublishStatus", ctx, status)}
}

func (_c *MockMQTTClient_PublishStatus_Call) Run(run func(ctx context.Context, status mqtt.Status)) *MockMQTTClient_PublishStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 mqtt.Status
		if args[1] != nil {
			arg1 = args[1].(mqtt.Status)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMQTTClient_PublishStatus_Call) Return(err error) *MockMQTTClient_PublishStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMQTTClient_PublishStatus_Call) RunAndReturn(run func(ctx context.Context, status mqtt.Status) error) *MockMQTTClient_PublishStatus_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function for the type MockMQTTClient
func (_mock *MockMQTTClient) Start(ctx context.Context, pauseFlag *atomic.Bool, triggerFn func()) error {
	ret := _mock.Called(ctx, pauseFlag, triggerFn)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *atomic.Bool, func()) error); ok {
		r0 = returnFunc(ctx, pauseFlag, triggerFn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMQTTClient_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockMQTTClient_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
//   - pauseFlag *atomic.Bool
//   - triggerFn func()
func (_e *MockMQTTClient_Expecter) Start(ctx interface{}, pauseFlag interface{}, triggerFn interface{}) *MockMQTTClient_Start_Call {
	return &MockMQTTClient_Start_Call{Call: _e.mock.On("Start", ctx, pauseFlag, triggerFn)}
}

func (_c *MockMQTTClient_Start_Call) Run(run func(ctx context.Context, pauseFlag *atomic.Bool, triggerFn func())) *MockMQTTClient_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *atomic.Bool
		if args[1] != nil {
			arg1 = args[1].(*atomic.Bool)
		}
		var arg2 func()
		if args[2] != nil {
			arg2 = args[2].(func())
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMQTTClient_Start_Call) Return(err error) *MockMQTTClient_Start_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMQTTClient_Start_Call) RunAndReturn(run func(ctx context.Context, pauseFlag *atomic.Bool, triggerFn func()) error) *MockMQTTClient_Start_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDeploymentReporter creates a new instance of MockDeploymentReporter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDeploymentReporter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDeploymentReporter {
	mock := &MockDeploymentReporter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDeploymentReporter is an autogenerated mock type for the DeploymentReporter type
type MockDeploymentReporter struct {
	mock.Mock
}

type MockDeploymentReporter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDeploymentReporter) EXPECT() *MockDeploymentReporter_Expecter {
	return &MockDeploymentReporter_Expecter{mock: &_m.Mock}
}

// CreateDeployment provides a mock function for the type MockDeploymentReporter
func (_mock *MockDeploymentReporter) CreateDeployment(ctx context.Context, sha string) (int64, error) {
	ret := _mock.Called(ctx, sha)

	if len(ret) == 0 {
		panic("no return value specified for CreateDeployment")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return returnFunc(ctx, sha)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = returnFunc(ctx, sha)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, sha)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDeploymentReporter_CreateDeployment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateDeployment'
type MockDeploymentReporter_CreateDeployment_Call struct {
	*mock.Call
}

// CreateDeployment is a helper method to define mock.On call
//   - ctx context.Context
//   - sha string
func (_e *MockDeploymentReporter_Expecter) CreateDeployment(ctx interface{}, sha interface{}) *MockDeploymentReporter_CreateDeployment_Call {
	return &MockDeploymentReporter_CreateDeployment_Call{Call: _e.mock.On("CreateDeployment", ctx, sha)}
}

func (_c *MockDeploymentReporter_CreateDeployment_Call) Run(run func(ctx context.Context, sha string)) *MockDeploymentReporter_CreateDeployment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDeploymentReporter_CreateDeployment_Call) Return(n int64, err error) *MockDeploymentReporter_CreateDeployment_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockDeploymentReporter_CreateDeployment_Call) RunAndReturn(run func(ctx context.Context, sha string) (int64, error)) *MockDeploymentReporter_CreateDeployment_Call {
	_c.Call.Return(run)
	return _c
}

// ReportError provides a mock function for the type MockDeploymentReporter
func (_mock *MockDeploymentReporter) ReportError(ctx context.Context, deploymentID int64, err error) error {
	ret := _mock.Called(ctx, deploymentID, err)

	if len(ret) == 0 {
		panic("no return value specified for ReportError")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, error) error); ok {
		r0 = returnFunc(ctx, deploymentID, err)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDeploymentReporter_ReportError_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReportError'
type MockDeploymentReporter_ReportError_Call struct {
	*mock.Call
}

// ReportError is a helper method to define mock.On call
//   - ctx context.Context
//   - deploymentID int64
//   - err error
func (_e *MockDeploymentReporter_Expecter) ReportError(ctx interface{}, deploymentID interface{}, err interface{}) *MockDeploymentReporter_ReportError_Call {
	return &MockDeploymentReporter_ReportError_Call{Call: _e.mock.On("ReportError", ctx, deploymentID, err)}
}

func (_c *MockDeploymentReporter_ReportError_Call) Run(run func(ctx context.Context, deploymentID int64, err error)) *MockDeploymentReporter_ReportError_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 error
		if args[2] != nil {
			arg2 = args[2].(error)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockDeploymentReporter_ReportError_Call) Return(err1 error) *MockDeploymentReporter_ReportError_Call {
	_c.Call.Return(err1)
	return _c
}

func (_c *MockDeploymentReporter_ReportError_Call) RunAndReturn(run func(ctx context.Context, deploymentID int64, err error) error) *MockDeploymentReporter_ReportError_Call {
	_c.Call.Return(run)
	return _c
}

// ReportFailure provides a mock function for the type MockDeploymentReporter
func (_mock *MockDeploymentReporter) ReportFailure(ctx context.Context, deploymentID int64, err error) error {
	ret := _mock.Called(ctx, deploymentID, err)

	if len(ret) == 0 {
		panic("no return value specified for ReportFailure")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, error) error); ok {
		r0 = returnFunc(ctx, deploymentID, err)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDeploymentReporter_ReportFailure_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReportFailure'
type MockDeploymentReporter_ReportFailure_Call struct {
	*mock.Call
}

// ReportFailure is a helper method to define mock.On call
//   - ctx context.Context
//   - deploymentID int64
//   - err error
func (_e *MockDeploymentReporter_Expecter) ReportFailure(ctx interface{}, deploymentID interface{}, err interface{}) *MockDeploymentReporter_ReportFailure_Call {
	return &MockDeploymentReporter_ReportFailure_Call{Call: _e.mock.On("ReportFailure", ctx, deploymentID, err)}
}

func (_c *MockDeploymentReporter_ReportFailure_Call) Run(run func(ctx context.Context, deploymentID int64, err error)) *MockDeploymentReporter_ReportFailure_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 error
		if args[2] != nil {
			arg2 = args[2].(error)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockDeploymentReporter_ReportFailure_Call) Return(err1 error) *MockDeploymentReporter_ReportFailure_Call {
	_c.Call.Return(err1)
	return _c
}

func (_c *MockDeploymentReporter_ReportFailure_Call) RunAndReturn(run func(ctx context.Context, deploymentID int64, err error) error) *MockDeploymentReporter_ReportFailure_Call {
	_c.Call.Return(run)
	return _c
}

// ReportInProgress provides a mock function for the type MockDeploymentReporter
func (_mock *MockDeploymentReporter) ReportInProgress(ctx context.Context, deploymentID int64) error {
	ret := _mock.Called(ctx, deploymentID)

	if len(ret) == 0 {
		panic("no return value specified for ReportInProgress")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, deploymentID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDeploymentReporter_ReportInProgress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReportInProgress'
type MockDeploymentReporter_ReportInProgress_Call struct {
	*mock.Call
}

// ReportInProgress is a helper method to define mock.On call
//   - ctx context.Context
//   - deploymentID int64
func (_e *MockDeploymentReporter_Expecter) ReportInProgress(ctx interface{}, deploymentID interface{}) *MockDeploymentReporter_ReportInProgress_Call {
	return &MockDeploymentReporter_ReportInProgress_Call{Call: _e.mock.On("ReportInProgress", ctx, deploymentID)}
}

func (_c *MockDeploymentReporter_ReportInProgress_Call) Run(run func(ctx context.Context, deploymentID int64)) *MockDeploymentReporter_ReportInProgress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDeploymentReporter_ReportInProgress_Call) Return(err error) *MockDeploymentReporter_ReportInProgress_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDeploymentReporter_ReportInProgress_Call) RunAndReturn(run func(ctx context.Context, deploymentID int64) error) *MockDeploymentReporter_ReportInProgress_Call {
	_c.Call.Return(run)
	return _c
}

// ReportSuccess provides a mock function for the type MockDeploymentReporter
func (_mock *MockDeploymentReporter) ReportSuccess(ctx context.Context, deploymentID int64) error {
	ret := _mock.Called(ctx, deploymentID)

	if len(ret) == 0 {
		panic("no return value specified for ReportSuccess")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, deploymentID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDeploymentReporter_ReportSuccess_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReportSuccess'
type MockDeploymentReporter_ReportSuccess_Call struct {
	*mock.Call
}

// ReportSuccess is a helper method to define mock.On call
//   - ctx context.Context
//   - deploymentID int64
func (_e *MockDeploymentReporter_Expecter) ReportSuccess(ctx interface{}, deploymentID interface{}) *MockDeploymentReporter_ReportSuccess_Call {
	return &MockDeploymentReporter_ReportSuccess_Call{Call: _e.mock.On("ReportSuccess", ctx, deploymentID)}
}

func (_c *MockDeploymentReporter_ReportSuccess_Call) Run(run func(ctx context.Context, deploymentID int64)) *MockDeploymentReporter_ReportSuccess_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDeploymentReporter_ReportSuccess_Call) Return(err error) *MockDeploymentReporter_ReportSuccess_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDeploymentReporter_ReportSuccess_Call) RunAndReturn(run func(ctx context.Context, deploymentID int64) error) *MockDeploymentReporter_ReportSuccess_Call {
	_c.Call.Return(run)
	return _c
}
