// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package protonpass

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// newMockcmdRunner creates a new instance of mockcmdRunner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockcmdRunner(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockcmdRunner {
	mock := &mockcmdRunner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockcmdRunner is an autogenerated mock type for the cmdRunner type
type mockcmdRunner struct {
	mock.Mock
}

type mockcmdRunner_Expecter struct {
	mock *mock.Mock
}

func (_m *mockcmdRunner) EXPECT() *mockcmdRunner_Expecter {
	return &mockcmdRunner_Expecter{mock: &_m.Mock}
}

// Run provides a mock function for the type mockcmdRunner
func (_mock *mockcmdRunner) Run(ctx context.Context, env []string, name string, args ...string) ([]byte, []byte, error) {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(ctx, env, name, args)
	} else {
		tmpRet = _mock.Called(ctx, env, name)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 []byte
	var r1 []byte
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, string, ...string) ([]byte, []byte, error)); ok {
		return returnFunc(ctx, env, name, args...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, string, ...string) []byte); ok {
		r0 = returnFunc(ctx, env, name, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string, string, ...string) []byte); ok {
		r1 = returnFunc(ctx, env, name, args...)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, []string, string, ...string) error); ok {
		r2 = returnFunc(ctx, env, name, args...)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// mockcmdRunner_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type mockcmdRunner_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx context.Context
//   - env []string
//   - name string
//   - args ...string
func (_e *mockcmdRunner_Expecter) Run(ctx interface{}, env interface{}, name interface{}, args ...interface{}) *mockcmdRunner_Run_Call {
	return &mockcmdRunner_Run_Call{Call: _e.mock.On("Run",
		append([]interface{}{ctx, env, name}, args...)...)}
}

func (_c *mockcmdRunner_Run_Call) Run(run func(ctx context.Context, env []string, name string, args ...string)) *mockcmdRunner_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []string
		var variadicArgs []string
		if len(args) > 3 {
			variadicArgs = args[3].([]string)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *mockcmdRunner_Run_Call) Return(stdout []byte, stderr []byte, err error) *mockcmdRunner_Run_Call {
	_c.Call.Return(stdout, stderr, err)
	return _c
}

func (_c *mockcmdRunner_Run_Call) RunAndReturn(run func(ctx context.Context, env []string, name string, args ...string) ([]byte, []byte, error)) *mockcmdRunner_Run_Call {
	_c.Call.Return(run)
	return _c
}
