// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"io/fs"

	"github.com/schjan/picolet/pkg/machine"
	mock "github.com/stretchr/testify/mock"
)

// NewMockHostOps creates a new instance of MockHostOps. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHostOps(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHostOps {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockHostOps{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockHostOps is an autogenerated mock type for the HostOps type
type MockHostOps struct {
	mock.Mock
}

type MockHostOps_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHostOps) EXPECT() *MockHostOps_Expecter {
	return &MockHostOps_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function for the type MockHostOps
func (_mock *MockHostOps) CreateUser(ctx context.Context, name string) error {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHostOps_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockHostOps_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockHostOps_Expecter) CreateUser(ctx any, name any) *MockHostOps_CreateUser_Call {
	return &MockHostOps_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, name)}
}

func (_c *MockHostOps_CreateUser_Call) Run(run func(ctx context.Context, name string)) *MockHostOps_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHostOps_CreateUser_Call) Return(err error) *MockHostOps_CreateUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHostOps_CreateUser_Call) RunAndReturn(run func(ctx context.Context, name string) error) *MockHostOps_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// EnableLinger provides a mock function for the type MockHostOps
func (_mock *MockHostOps) EnableLinger(ctx context.Context, user machine.User) error {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for EnableLinger")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, machine.User) error); ok {
		r0 = returnFunc(ctx, user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHostOps_EnableLinger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnableLinger'
type MockHostOps_EnableLinger_Call struct {
	*mock.Call
}

// EnableLinger is a helper method to define mock.On call
//   - ctx context.Context
//   - user machine.User
func (_e *MockHostOps_Expecter) EnableLinger(ctx any, user any) *MockHostOps_EnableLinger_Call {
	return &MockHostOps_EnableLinger_Call{Call: _e.mock.On("EnableLinger", ctx, user)}
}

func (_c *MockHostOps_EnableLinger_Call) Run(run func(ctx context.Context, user machine.User)) *MockHostOps_EnableLinger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 machine.User
		if args[1] != nil {
			arg1 = args[1].(machine.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHostOps_EnableLinger_Call) Return(err error) *MockHostOps_EnableLinger_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHostOps_EnableLinger_Call) RunAndReturn(run func(ctx context.Context, user machine.User) error) *MockHostOps_EnableLinger_Call {
	_c.Call.Return(run)
	return _c
}

// EnableSystemUnit provides a mock function for the type MockHostOps
func (_mock *MockHostOps) EnableSystemUnit(ctx context.Context, unit string) error {
	ret := _mock.Called(ctx, unit)

	if len(ret) == 0 {
		panic("no return value specified for EnableSystemUnit")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, unit)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHostOps_EnableSystemUnit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnableSystemUnit'
type MockHostOps_EnableSystemUnit_Call struct {
	*mock.Call
}

// EnableSystemUnit is a helper method to define mock.On call
//   - ctx context.Context
//   - unit string
func (_e *MockHostOps_Expecter) EnableSystemUnit(ctx any, unit any) *MockHostOps_EnableSystemUnit_Call {
	return &MockHostOps_EnableSystemUnit_Call{Call: _e.mock.On("EnableSystemUnit", ctx, unit)}
}

func (_c *MockHostOps_EnableSystemUnit_Call) Run(run func(ctx context.Context, unit string)) *MockHostOps_EnableSystemUnit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHostOps_EnableSystemUnit_Call) Return(err error) *MockHostOps_EnableSystemUnit_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHostOps_EnableSystemUnit_Call) RunAndReturn(run func(ctx context.Context, unit string) error) *MockHostOps_EnableSystemUnit_Call {
	_c.Call.Return(run)
	return _c
}

// EnableUserUnit provides a mock function for the type MockHostOps
func (_mock *MockHostOps) EnableUserUnit(ctx context.Context, user machine.User, unit string) error {
	ret := _mock.Called(ctx, user, unit)

	if len(ret) == 0 {
		panic("no return value specified for EnableUserUnit")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, machine.User, string) error); ok {
		r0 = returnFunc(ctx, user, unit)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHostOps_EnableUserUnit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnableUserUnit'
type MockHostOps_EnableUserUnit_Call struct {
	*mock.Call
}

// EnableUserUnit is a helper method to define mock.On call
//   - ctx context.Context
//   - user machine.User
//   - unit string
func (_e *MockHostOps_Expecter) EnableUserUnit(ctx any, user any, unit any) *MockHostOps_EnableUserUnit_Call {
	return &MockHostOps_EnableUserUnit_Call{Call: _e.mock.On("EnableUserUnit", ctx, user, unit)}
}

func (_c *MockHostOps_EnableUserUnit_Call) Run(run func(ctx context.Context, user machine.User, unit string)) *MockHostOps_EnableUserUnit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 machine.User
		if args[1] != nil {
			arg1 = args[1].(machine.User)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockHostOps_EnableUserUnit_Call) Return(err error) *MockHostOps_EnableUserUnit_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHostOps_EnableUserUnit_Call) RunAndReturn(run func(ctx context.Context, user machine.User, unit string) error) *MockHostOps_EnableUserUnit_Call {
	_c.Call.Return(run)
	return _c
}

// EnsureDir provides a mock function for the type MockHostOps
func (_mock *MockHostOps) EnsureDir(base string, rel string, owner machine.Owner, mode fs.FileMode) error {
	ret := _mock.Called(base, rel, owner, mode)

	if len(ret) == 0 {
		panic("no return value specified for EnsureDir")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string, machine.Owner, fs.FileMode) error); ok {
		r0 = returnFunc(base, rel, owner, mode)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHostOps_EnsureDir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnsureDir'
type MockHostOps_EnsureDir_Call struct {
	*mock.Call
}

// EnsureDir is a helper method to define mock.On call
//   - base string
//   - rel string
//   - owner machine.Owner
//   - mode fs.FileMode
func (_e *MockHostOps_Expecter) EnsureDir(base any, rel any, owner any, mode any) *MockHostOps_EnsureDir_Call {
	return &MockHostOps_EnsureDir_Call{Call: _e.mock.On("EnsureDir", base, rel, owner, mode)}
}

func (_c *MockHostOps_EnsureDir_Call) Run(run func(base string, rel string, owner machine.Owner, mode fs.FileMode)) *MockHostOps_EnsureDir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 machine.Owner
		if args[2] != nil {
			arg2 = args[2].(machine.Owner)
		}
		var arg3 fs.FileMode
		if args[3] != nil {
			arg3 = args[3].(fs.FileMode)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockHostOps_EnsureDir_Call) Return(err error) *MockHostOps_EnsureDir_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHostOps_EnsureDir_Call) RunAndReturn(run func(base string, rel string, owner machine.Owner, mode fs.FileMode) error) *MockHostOps_EnsureDir_Call {
	_c.Call.Return(run)
	return _c
}

// FileContentEquals provides a mock function for the type MockHostOps
func (_mock *MockHostOps) FileContentEquals(path string, content []byte) (bool, error) {
	ret := _mock.Called(path, content)

	if len(ret) == 0 {
		panic("no return value specified for FileContentEquals")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, []byte) (bool, error)); ok {
		return returnFunc(path, content)
	}
	if returnFunc, ok := ret.Get(0).(func(string, []byte) bool); ok {
		r0 = returnFunc(path, content)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(string, []byte) error); ok {
		r1 = returnFunc(path, content)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHostOps_FileContentEquals_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FileContentEquals'
type MockHostOps_FileContentEquals_Call struct {
	*mock.Call
}

// FileContentEquals is a helper method to define mock.On call
//   - path string
//   - content []byte
func (_e *MockHostOps_Expecter) FileContentEquals(path any, content any) *MockHostOps_FileContentEquals_Call {
	return &MockHostOps_FileContentEquals_Call{Call: _e.mock.On("FileContentEquals", path, content)}
}

func (_c *MockHostOps_FileContentEquals_Call) Run(run func(path string, content []byte)) *MockHostOps_FileContentEquals_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHostOps_FileContentEquals_Call) Return(b bool, err error) *MockHostOps_FileContentEquals_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockHostOps_FileContentEquals_Call) RunAndReturn(run func(path string, content []byte) (bool, error)) *MockHostOps_FileContentEquals_Call {
	_c.Call.Return(run)
	return _c
}

// LingerEnabled provides a mock function for the type MockHostOps
func (_mock *MockHostOps) LingerEnabled(user machine.User) (bool, error) {
	ret := _mock.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for LingerEnabled")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(machine.User) (bool, error)); ok {
		return returnFunc(user)
	}
	if returnFunc, ok := ret.Get(0).(func(machine.User) bool); ok {
		r0 = returnFunc(user)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(machine.User) error); ok {
		r1 = returnFunc(user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHostOps_LingerEnabled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LingerEnabled'
type MockHostOps_LingerEnabled_Call struct {
	*mock.Call
}

// LingerEnabled is a helper method to define mock.On call
//   - user machine.User
func (_e *MockHostOps_Expecter) LingerEnabled(user any) *MockHostOps_LingerEnabled_Call {
	return &MockHostOps_LingerEnabled_Call{Call: _e.mock.On("LingerEnabled", user)}
}

func (_c *MockHostOps_LingerEnabled_Call) Run(run func(user machine.User)) *MockHostOps_LingerEnabled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 machine.User
		if args[0] != nil {
			arg0 = args[0].(machine.User)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHostOps_LingerEnabled_Call) Return(b bool, err error) *MockHostOps_LingerEnabled_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockHostOps_LingerEnabled_Call) RunAndReturn(run func(user machine.User) (bool, error)) *MockHostOps_LingerEnabled_Call {
	_c.Call.Return(run)
	return _c
}

// LookupUser provides a mock function for the type MockHostOps
func (_mock *MockHostOps) LookupUser(name string) (machine.User, bool, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for LookupUser")
	}

	var r0 machine.User
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(string) (machine.User, bool, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) machine.User); ok {
		r0 = returnFunc(name)
	} else {
		r0 = ret.Get(0).(machine.User)
	}
	if returnFunc, ok := ret.Get(1).(func(string) bool); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(string) error); ok {
		r2 = returnFunc(name)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockHostOps_LookupUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LookupUser'
type MockHostOps_LookupUser_Call struct {
	*mock.Call
}

// LookupUser is a helper method to define mock.On call
//   - name string
func (_e *MockHostOps_Expecter) LookupUser(name any) *MockHostOps_LookupUser_Call {
	return &MockHostOps_LookupUser_Call{Call: _e.mock.On("LookupUser", name)}
}

func (_c *MockHostOps_LookupUser_Call) Run(run func(name string)) *MockHostOps_LookupUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHostOps_LookupUser_Call) Return(user machine.User, found bool, err error) *MockHostOps_LookupUser_Call {
	_c.Call.Return(user, found, err)
	return _c
}

func (_c *MockHostOps_LookupUser_Call) RunAndReturn(run func(name string) (machine.User, bool, error)) *MockHostOps_LookupUser_Call {
	_c.Call.Return(run)
	return _c
}

// MakeWorldReadable provides a mock function for the type MockHostOps
func (_mock *MockHostOps) MakeWorldReadable(path string) error {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for MakeWorldReadable")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(path)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHostOps_MakeWorldReadable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MakeWorldReadable'
type MockHostOps_MakeWorldReadable_Call struct {
	*mock.Call
}

// MakeWorldReadable is a helper method to define mock.On call
//   - path string
func (_e *MockHostOps_Expecter) MakeWorldReadable(path any) *MockHostOps_MakeWorldReadable_Call {
	return &MockHostOps_MakeWorldReadable_Call{Call: _e.mock.On("MakeWorldReadable", path)}
}

func (_c *MockHostOps_MakeWorldReadable_Call) Run(run func(path string)) *MockHostOps_MakeWorldReadable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHostOps_MakeWorldReadable_Call) Return(err error) *MockHostOps_MakeWorldReadable_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHostOps_MakeWorldReadable_Call) RunAndReturn(run func(path string) error) *MockHostOps_MakeWorldReadable_Call {
	_c.Call.Return(run)
	return _c
}

// RestartSystemUnit provides a mock function for the type MockHostOps
func (_mock *MockHostOps) RestartSystemUnit(ctx context.Context, unit string) error {
	ret := _mock.Called(ctx, unit)

	if len(ret) == 0 {
		panic("no return value specified for RestartSystemUnit")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, unit)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHostOps_RestartSystemUnit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RestartSystemUnit'
type MockHostOps_RestartSystemUnit_Call struct {
	*mock.Call
}

// RestartSystemUnit is a helper method to define mock.On call
//   - ctx context.Context
//   - unit string
func (_e *MockHostOps_Expecter) RestartSystemUnit(ctx any, unit any) *MockHostOps_RestartSystemUnit_Call {
	return &MockHostOps_RestartSystemUnit_Call{Call: _e.mock.On("RestartSystemUnit", ctx, unit)}
}

func (_c *MockHostOps_RestartSystemUnit_Call) Run(run func(ctx context.Context, unit string)) *MockHostOps_RestartSystemUnit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHostOps_RestartSystemUnit_Call) Return(err error) *MockHostOps_RestartSystemUnit_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHostOps_RestartSystemUnit_Call) RunAndReturn(run func(ctx context.Context, unit string) error) *MockHostOps_RestartSystemUnit_Call {
	_c.Call.Return(run)
	return _c
}

// RestartUserUnit provides a mock function for the type MockHostOps
func (_mock *MockHostOps) RestartUserUnit(ctx context.Context, user machine.User, unit string) error {
	ret := _mock.Called(ctx, user, unit)

	if len(ret) == 0 {
		panic("no return value specified for RestartUserUnit")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, machine.User, string) error); ok {
		r0 = returnFunc(ctx, user, unit)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHostOps_RestartUserUnit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RestartUserUnit'
type MockHostOps_RestartUserUnit_Call struct {
	*mock.Call
}

// RestartUserUnit is a helper method to define mock.On call
//   - ctx context.Context
//   - user machine.User
//   - unit string
func (_e *MockHostOps_Expecter) RestartUserUnit(ctx any, user any, unit any) *MockHostOps_RestartUserUnit_Call {
	return &MockHostOps_RestartUserUnit_Call{Call: _e.mock.On("RestartUserUnit", ctx, user, unit)}
}

func (_c *MockHostOps_RestartUserUnit_Call) Run(run func(ctx context.Context, user machine.User, unit string)) *MockHostOps_RestartUserUnit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 machine.User
		if args[1] != nil {
			arg1 = args[1].(machine.User)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockHostOps_RestartUserUnit_Call) Return(err error) *MockHostOps_RestartUserUnit_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHostOps_RestartUserUnit_Call) RunAndReturn(run func(ctx context.Context, user machine.User, unit string) error) *MockHostOps_RestartUserUnit_Call {
	_c.Call.Return(run)
	return _c
}

// RunAsRoot provides a mock function for the type MockHostOps
func (_mock *MockHostOps) RunAsRoot(ctx context.Context, cmd machine.Command) error {
	ret := _mock.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for RunAsRoot")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, machine.Command) error); ok {
		r0 = returnFunc(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHostOps_RunAsRoot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunAsRoot'
type MockHostOps_RunAsRoot_Call struct {
	*mock.Call
}

// RunAsRoot is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd machine.Command
func (_e *MockHostOps_Expecter) RunAsRoot(ctx any, cmd any) *MockHostOps_RunAsRoot_Call {
	return &MockHostOps_RunAsRoot_Call{Call: _e.mock.On("RunAsRoot", ctx, cmd)}
}

func (_c *MockHostOps_RunAsRoot_Call) Run(run func(ctx context.Context, cmd machine.Command)) *MockHostOps_RunAsRoot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 machine.Command
		if args[1] != nil {
			arg1 = args[1].(machine.Command)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHostOps_RunAsRoot_Call) Return(err error) *MockHostOps_RunAsRoot_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHostOps_RunAsRoot_Call) RunAndReturn(run func(ctx context.Context, cmd machine.Command) error) *MockHostOps_RunAsRoot_Call {
	_c.Call.Return(run)
	return _c
}

// RunAsUser provides a mock function for the type MockHostOps
func (_mock *MockHostOps) RunAsUser(ctx context.Context, user machine.User, cmd machine.Command) error {
	ret := _mock.Called(ctx, user, cmd)

	if len(ret) == 0 {
		panic("no return value specified for RunAsUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, machine.User, machine.Command) error); ok {
		r0 = returnFunc(ctx, user, cmd)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHostOps_RunAsUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunAsUser'
type MockHostOps_RunAsUser_Call struct {
	*mock.Call
}

// RunAsUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user machine.User
//   - cmd machine.Command
func (_e *MockHostOps_Expecter) RunAsUser(ctx any, user any, cmd any) *MockHostOps_RunAsUser_Call {
	return &MockHostOps_RunAsUser_Call{Call: _e.mock.On("RunAsUser", ctx, user, cmd)}
}

func (_c *MockHostOps_RunAsUser_Call) Run(run func(ctx context.Context, user machine.User, cmd machine.Command)) *MockHostOps_RunAsUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 machine.User
		if args[1] != nil {
			arg1 = args[1].(machine.User)
		}
		var arg2 machine.Command
		if args[2] != nil {
			arg2 = args[2].(machine.Command)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockHostOps_RunAsUser_Call) Return(err error) *MockHostOps_RunAsUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHostOps_RunAsUser_Call) RunAndReturn(run func(ctx context.Context, user machine.User, cmd machine.Command) error) *MockHostOps_RunAsUser_Call {
	_c.Call.Return(run)
	return _c
}

// SetOwnerMode provides a mock function for the type MockHostOps
func (_mock *MockHostOps) SetOwnerMode(base string, rel string, owner machine.Owner, mode fs.FileMode) error {
	ret := _mock.Called(base, rel, owner, mode)

	if len(ret) == 0 {
		panic("no return value specified for SetOwnerMode")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string, machine.Owner, fs.FileMode) error); ok {
		r0 = returnFunc(base, rel, owner, mode)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHostOps_SetOwnerMode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetOwnerMode'
type MockHostOps_SetOwnerMode_Call struct {
	*mock.Call
}

// SetOwnerMode is a helper method to define mock.On call
//   - base string
//   - rel string
//   - owner machine.Owner
//   - mode fs.FileMode
func (_e *MockHostOps_Expecter) SetOwnerMode(base any, rel any, owner any, mode any) *MockHostOps_SetOwnerMode_Call {
	return &MockHostOps_SetOwnerMode_Call{Call: _e.mock.On("SetOwnerMode", base, rel, owner, mode)}
}

func (_c *MockHostOps_SetOwnerMode_Call) Run(run func(base string, rel string, owner machine.Owner, mode fs.FileMode)) *MockHostOps_SetOwnerMode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 machine.Owner
		if args[2] != nil {
			arg2 = args[2].(machine.Owner)
		}
		var arg3 fs.FileMode
		if args[3] != nil {
			arg3 = args[3].(fs.FileMode)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockHostOps_SetOwnerMode_Call) Return(err error) *MockHostOps_SetOwnerMode_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHostOps_SetOwnerMode_Call) RunAndReturn(run func(base string, rel string, owner machine.Owner, mode fs.FileMode) error) *MockHostOps_SetOwnerMode_Call {
	_c.Call.Return(run)
	return _c
}

// Stat provides a mock function for the type MockHostOps
func (_mock *MockHostOps) Stat(path string) (machine.PathInfo, error) {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for Stat")
	}

	var r0 machine.PathInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (machine.PathInfo, error)); ok {
		return returnFunc(path)
	}
	if returnFunc, ok := ret.Get(0).(func(string) machine.PathInfo); ok {
		r0 = returnFunc(path)
	} else {
		r0 = ret.Get(0).(machine.PathInfo)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHostOps_Stat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stat'
type MockHostOps_Stat_Call struct {
	*mock.Call
}

// Stat is a helper method to define mock.On call
//   - path string
func (_e *MockHostOps_Expecter) Stat(path any) *MockHostOps_Stat_Call {
	return &MockHostOps_Stat_Call{Call: _e.mock.On("Stat", path)}
}

func (_c *MockHostOps_Stat_Call) Run(run func(path string)) *MockHostOps_Stat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHostOps_Stat_Call) Return(pathInfo machine.PathInfo, err error) *MockHostOps_Stat_Call {
	_c.Call.Return(pathInfo, err)
	return _c
}

func (_c *MockHostOps_Stat_Call) RunAndReturn(run func(path string) (machine.PathInfo, error)) *MockHostOps_Stat_Call {
	_c.Call.Return(run)
	return _c
}

// SubIDRanges provides a mock function for the type MockHostOps
func (_mock *MockHostOps) SubIDRanges(user machine.User) (bool, bool, error) {
	ret := _mock.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for SubIDRanges")
	}

	var r0 bool
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(machine.User) (bool, bool, error)); ok {
		return returnFunc(user)
	}
	if returnFunc, ok := ret.Get(0).(func(machine.User) bool); ok {
		r0 = returnFunc(user)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(machine.User) bool); ok {
		r1 = returnFunc(user)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(machine.User) error); ok {
		r2 = returnFunc(user)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockHostOps_SubIDRanges_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SubIDRanges'
type MockHostOps_SubIDRanges_Call struct {
	*mock.Call
}

// SubIDRanges is a helper method to define mock.On call
//   - user machine.User
func (_e *MockHostOps_Expecter) SubIDRanges(user any) *MockHostOps_SubIDRanges_Call {
	return &MockHostOps_SubIDRanges_Call{Call: _e.mock.On("SubIDRanges", user)}
}

func (_c *MockHostOps_SubIDRanges_Call) Run(run func(user machine.User)) *MockHostOps_SubIDRanges_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 machine.User
		if args[0] != nil {
			arg0 = args[0].(machine.User)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHostOps_SubIDRanges_Call) Return(subuid bool, subgid bool, err error) *MockHostOps_SubIDRanges_Call {
	_c.Call.Return(subuid, subgid, err)
	return _c
}

func (_c *MockHostOps_SubIDRanges_Call) RunAndReturn(run func(user machine.User) (bool, bool, error)) *MockHostOps_SubIDRanges_Call {
	_c.Call.Return(run)
	return _c
}

// SystemUnitState provides a mock function for the type MockHostOps
func (_mock *MockHostOps) SystemUnitState(ctx context.Context, unit string) (machine.UnitState, error) {
	ret := _mock.Called(ctx, unit)

	if len(ret) == 0 {
		panic("no return value specified for SystemUnitState")
	}

	var r0 machine.UnitState
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (machine.UnitState, error)); ok {
		return returnFunc(ctx, unit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) machine.UnitState); ok {
		r0 = returnFunc(ctx, unit)
	} else {
		r0 = ret.Get(0).(machine.UnitState)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, unit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHostOps_SystemUnitState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SystemUnitState'
type MockHostOps_SystemUnitState_Call struct {
	*mock.Call
}

// SystemUnitState is a helper method to define mock.On call
//   - ctx context.Context
//   - unit string
func (_e *MockHostOps_Expecter) SystemUnitState(ctx any, unit any) *MockHostOps_SystemUnitState_Call {
	return &MockHostOps_SystemUnitState_Call{Call: _e.mock.On("SystemUnitState", ctx, unit)}
}

func (_c *MockHostOps_SystemUnitState_Call) Run(run func(ctx context.Context, unit string)) *MockHostOps_SystemUnitState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHostOps_SystemUnitState_Call) Return(unitState machine.UnitState, err error) *MockHostOps_SystemUnitState_Call {
	_c.Call.Return(unitState, err)
	return _c
}

func (_c *MockHostOps_SystemUnitState_Call) RunAndReturn(run func(ctx context.Context, unit string) (machine.UnitState, error)) *MockHostOps_SystemUnitState_Call {
	_c.Call.Return(run)
	return _c
}

// UserManagerRunning provides a mock function for the type MockHostOps
func (_mock *MockHostOps) UserManagerRunning(user machine.User) (bool, error) {
	ret := _mock.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for UserManagerRunning")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(machine.User) (bool, error)); ok {
		return returnFunc(user)
	}
	if returnFunc, ok := ret.Get(0).(func(machine.User) bool); ok {
		r0 = returnFunc(user)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(machine.User) error); ok {
		r1 = returnFunc(user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHostOps_UserManagerRunning_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserManagerRunning'
type MockHostOps_UserManagerRunning_Call struct {
	*mock.Call
}

// UserManagerRunning is a helper method to define mock.On call
//   - user machine.User
func (_e *MockHostOps_Expecter) UserManagerRunning(user any) *MockHostOps_UserManagerRunning_Call {
	return &MockHostOps_UserManagerRunning_Call{Call: _e.mock.On("UserManagerRunning", user)}
}

func (_c *MockHostOps_UserManagerRunning_Call) Run(run func(user machine.User)) *MockHostOps_UserManagerRunning_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 machine.User
		if args[0] != nil {
			arg0 = args[0].(machine.User)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHostOps_UserManagerRunning_Call) Return(b bool, err error) *MockHostOps_UserManagerRunning_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockHostOps_UserManagerRunning_Call) RunAndReturn(run func(user machine.User) (bool, error)) *MockHostOps_UserManagerRunning_Call {
	_c.Call.Return(run)
	return _c
}

// UserUnitState provides a mock function for the type MockHostOps
func (_mock *MockHostOps) UserUnitState(ctx context.Context, user machine.User, unit string) (machine.UnitState, error) {
	ret := _mock.Called(ctx, user, unit)

	if len(ret) == 0 {
		panic("no return value specified for UserUnitState")
	}

	var r0 machine.UnitState
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, machine.User, string) (machine.UnitState, error)); ok {
		return returnFunc(ctx, user, unit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, machine.User, string) machine.UnitState); ok {
		r0 = returnFunc(ctx, user, unit)
	} else {
		r0 = ret.Get(0).(machine.UnitState)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, machine.User, string) error); ok {
		r1 = returnFunc(ctx, user, unit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHostOps_UserUnitState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserUnitState'
type MockHostOps_UserUnitState_Call struct {
	*mock.Call
}

// UserUnitState is a helper method to define mock.On call
//   - ctx context.Context
//   - user machine.User
//   - unit string
func (_e *MockHostOps_Expecter) UserUnitState(ctx any, user any, unit any) *MockHostOps_UserUnitState_Call {
	return &MockHostOps_UserUnitState_Call{Call: _e.mock.On("UserUnitState", ctx, user, unit)}
}

func (_c *MockHostOps_UserUnitState_Call) Run(run func(ctx context.Context, user machine.User, unit string)) *MockHostOps_UserUnitState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 machine.User
		if args[1] != nil {
			arg1 = args[1].(machine.User)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockHostOps_UserUnitState_Call) Return(unitState machine.UnitState, err error) *MockHostOps_UserUnitState_Call {
	_c.Call.Return(unitState, err)
	return _c
}

func (_c *MockHostOps_UserUnitState_Call) RunAndReturn(run func(ctx context.Context, user machine.User, unit string) (machine.UnitState, error)) *MockHostOps_UserUnitState_Call {
	_c.Call.Return(run)
	return _c
}

// WaitHealthy provides a mock function for the type MockHostOps
func (_mock *MockHostOps) WaitHealthy(ctx context.Context, addr string) error {
	ret := _mock.Called(ctx, addr)

	if len(ret) == 0 {
		panic("no return value specified for WaitHealthy")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, addr)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHostOps_WaitHealthy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WaitHealthy'
type MockHostOps_WaitHealthy_Call struct {
	*mock.Call
}

// WaitHealthy is a helper method to define mock.On call
//   - ctx context.Context
//   - addr string
func (_e *MockHostOps_Expecter) WaitHealthy(ctx any, addr any) *MockHostOps_WaitHealthy_Call {
	return &MockHostOps_WaitHealthy_Call{Call: _e.mock.On("WaitHealthy", ctx, addr)}
}

func (_c *MockHostOps_WaitHealthy_Call) Run(run func(ctx context.Context, addr string)) *MockHostOps_WaitHealthy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHostOps_WaitHealthy_Call) Return(err error) *MockHostOps_WaitHealthy_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHostOps_WaitHealthy_Call) RunAndReturn(run func(ctx context.Context, addr string) error) *MockHostOps_WaitHealthy_Call {
	_c.Call.Return(run)
	return _c
}

// WaitUserManager provides a mock function for the type MockHostOps
func (_mock *MockHostOps) WaitUserManager(ctx context.Context, user machine.User) error {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for WaitUserManager")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, machine.User) error); ok {
		r0 = returnFunc(ctx, user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHostOps_WaitUserManager_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WaitUserManager'
type MockHostOps_WaitUserManager_Call struct {
	*mock.Call
}

// WaitUserManager is a helper method to define mock.On call
//   - ctx context.Context
//   - user machine.User
func (_e *MockHostOps_Expecter) WaitUserManager(ctx any, user any) *MockHostOps_WaitUserManager_Call {
	return &MockHostOps_WaitUserManager_Call{Call: _e.mock.On("WaitUserManager", ctx, user)}
}

func (_c *MockHostOps_WaitUserManager_Call) Run(run func(ctx context.Context, user machine.User)) *MockHostOps_WaitUserManager_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 machine.User
		if args[1] != nil {
			arg1 = args[1].(machine.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHostOps_WaitUserManager_Call) Return(err error) *MockHostOps_WaitUserManager_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHostOps_WaitUserManager_Call) RunAndReturn(run func(ctx context.Context, user machine.User) error) *MockHostOps_WaitUserManager_Call {
	_c.Call.Return(run)
	return _c
}

// WorldReadableTree provides a mock function for the type MockHostOps
func (_mock *MockHostOps) WorldReadableTree(path string) (bool, error) {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for WorldReadableTree")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (bool, error)); ok {
		return returnFunc(path)
	}
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(path)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHostOps_WorldReadableTree_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WorldReadableTree'
type MockHostOps_WorldReadableTree_Call struct {
	*mock.Call
}

// WorldReadableTree is a helper method to define mock.On call
//   - path string
func (_e *MockHostOps_Expecter) WorldReadableTree(path any) *MockHostOps_WorldReadableTree_Call {
	return &MockHostOps_WorldReadableTree_Call{Call: _e.mock.On("WorldReadableTree", path)}
}

func (_c *MockHostOps_WorldReadableTree_Call) Run(run func(path string)) *MockHostOps_WorldReadableTree_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHostOps_WorldReadableTree_Call) Return(b bool, err error) *MockHostOps_WorldReadableTree_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockHostOps_WorldReadableTree_Call) RunAndReturn(run func(path string) (bool, error)) *MockHostOps_WorldReadableTree_Call {
	_c.Call.Return(run)
	return _c
}

// WriteFile provides a mock function for the type MockHostOps
func (_mock *MockHostOps) WriteFile(base string, rel string, content []byte, owner machine.Owner, mode fs.FileMode) error {
	ret := _mock.Called(base, rel, content, owner, mode)

	if len(ret) == 0 {
		panic("no return value specified for WriteFile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string, []byte, machine.Owner, fs.FileMode) error); ok {
		r0 = returnFunc(base, rel, content, owner, mode)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHostOps_WriteFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteFile'
type MockHostOps_WriteFile_Call struct {
	*mock.Call
}

// WriteFile is a helper method to define mock.On call
//   - base string
//   - rel string
//   - content []byte
//   - owner machine.Owner
//   - mode fs.FileMode
func (_e *MockHostOps_Expecter) WriteFile(base any, rel any, content any, owner any, mode any) *MockHostOps_WriteFile_Call {
	return &MockHostOps_WriteFile_Call{Call: _e.mock.On("WriteFile", base, rel, content, owner, mode)}
}

func (_c *MockHostOps_WriteFile_Call) Run(run func(base string, rel string, content []byte, owner machine.Owner, mode fs.FileMode)) *MockHostOps_WriteFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		var arg3 machine.Owner
		if args[3] != nil {
			arg3 = args[3].(machine.Owner)
		}
		var arg4 fs.FileMode
		if args[4] != nil {
			arg4 = args[4].(fs.FileMode)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockHostOps_WriteFile_Call) Return(err error) *MockHostOps_WriteFile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHostOps_WriteFile_Call) RunAndReturn(run func(base string, rel string, content []byte, owner machine.Owner, mode fs.FileMode) error) *MockHostOps_WriteFile_Call {
	_c.Call.Return(run)
	return _c
}
