// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/schjan/picolet/pkg/machine"
	mock "github.com/stretchr/testify/mock"
)

// NewMockHostOps creates a new instance of MockHostOps. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHostOps(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHostOps {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockHostOps{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockHostOps is an autogenerated mock type for the HostOps type
type MockHostOps struct {
	mock.Mock
}

type MockHostOps_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHostOps) EXPECT() *MockHostOps_Expecter {
	return &MockHostOps_Expecter{mock: &_m.Mock}
}

// FileContentEquals provides a mock function for the type MockHostOps
func (_mock *MockHostOps) FileContentEquals(path string, content []byte) (bool, error) {
	ret := _mock.Called(path, content)

	if len(ret) == 0 {
		panic("no return value specified for FileContentEquals")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, []byte) (bool, error)); ok {
		return returnFunc(path, content)
	}
	if returnFunc, ok := ret.Get(0).(func(string, []byte) bool); ok {
		r0 = returnFunc(path, content)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(string, []byte) error); ok {
		r1 = returnFunc(path, content)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHostOps_FileContentEquals_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FileContentEquals'
type MockHostOps_FileContentEquals_Call struct {
	*mock.Call
}

// FileContentEquals is a helper method to define mock.On call
//   - path string
//   - content []byte
func (_e *MockHostOps_Expecter) FileContentEquals(path any, content any) *MockHostOps_FileContentEquals_Call {
	return &MockHostOps_FileContentEquals_Call{Call: _e.mock.On("FileContentEquals", path, content)}
}

func (_c *MockHostOps_FileContentEquals_Call) Run(run func(path string, content []byte)) *MockHostOps_FileContentEquals_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHostOps_FileContentEquals_Call) Return(b bool, err error) *MockHostOps_FileContentEquals_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockHostOps_FileContentEquals_Call) RunAndReturn(run func(path string, content []byte) (bool, error)) *MockHostOps_FileContentEquals_Call {
	_c.Call.Return(run)
	return _c
}

// LingerEnabled provides a mock function for the type MockHostOps
func (_mock *MockHostOps) LingerEnabled(user machine.User) (bool, error) {
	ret := _mock.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for LingerEnabled")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(machine.User) (bool, error)); ok {
		return returnFunc(user)
	}
	if returnFunc, ok := ret.Get(0).(func(machine.User) bool); ok {
		r0 = returnFunc(user)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(machine.User) error); ok {
		r1 = returnFunc(user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHostOps_LingerEnabled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LingerEnabled'
type MockHostOps_LingerEnabled_Call struct {
	*mock.Call
}

// LingerEnabled is a helper method to define mock.On call
//   - user machine.User
func (_e *MockHostOps_Expecter) LingerEnabled(user any) *MockHostOps_LingerEnabled_Call {
	return &MockHostOps_LingerEnabled_Call{Call: _e.mock.On("LingerEnabled", user)}
}

func (_c *MockHostOps_LingerEnabled_Call) Run(run func(user machine.User)) *MockHostOps_LingerEnabled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 machine.User
		if args[0] != nil {
			arg0 = args[0].(machine.User)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHostOps_LingerEnabled_Call) Return(b bool, err error) *MockHostOps_LingerEnabled_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockHostOps_LingerEnabled_Call) RunAndReturn(run func(user machine.User) (bool, error)) *MockHostOps_LingerEnabled_Call {
	_c.Call.Return(run)
	return _c
}

// LookupUser provides a mock function for the type MockHostOps
func (_mock *MockHostOps) LookupUser(name string) (machine.User, bool, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for LookupUser")
	}

	var r0 machine.User
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(string) (machine.User, bool, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) machine.User); ok {
		r0 = returnFunc(name)
	} else {
		r0 = ret.Get(0).(machine.User)
	}
	if returnFunc, ok := ret.Get(1).(func(string) bool); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(string) error); ok {
		r2 = returnFunc(name)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockHostOps_LookupUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LookupUser'
type MockHostOps_LookupUser_Call struct {
	*mock.Call
}

// LookupUser is a helper method to define mock.On call
//   - name string
func (_e *MockHostOps_Expecter) LookupUser(name any) *MockHostOps_LookupUser_Call {
	return &MockHostOps_LookupUser_Call{Call: _e.mock.On("LookupUser", name)}
}

func (_c *MockHostOps_LookupUser_Call) Run(run func(name string)) *MockHostOps_LookupUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHostOps_LookupUser_Call) Return(user machine.User, found bool, err error) *MockHostOps_LookupUser_Call {
	_c.Call.Return(user, found, err)
	return _c
}

func (_c *MockHostOps_LookupUser_Call) RunAndReturn(run func(name string) (machine.User, bool, error)) *MockHostOps_LookupUser_Call {
	_c.Call.Return(run)
	return _c
}

// Stat provides a mock function for the type MockHostOps
func (_mock *MockHostOps) Stat(path string) (machine.PathInfo, error) {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for Stat")
	}

	var r0 machine.PathInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (machine.PathInfo, error)); ok {
		return returnFunc(path)
	}
	if returnFunc, ok := ret.Get(0).(func(string) machine.PathInfo); ok {
		r0 = returnFunc(path)
	} else {
		r0 = ret.Get(0).(machine.PathInfo)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHostOps_Stat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stat'
type MockHostOps_Stat_Call struct {
	*mock.Call
}

// Stat is a helper method to define mock.On call
//   - path string
func (_e *MockHostOps_Expecter) Stat(path any) *MockHostOps_Stat_Call {
	return &MockHostOps_Stat_Call{Call: _e.mock.On("Stat", path)}
}

func (_c *MockHostOps_Stat_Call) Run(run func(path string)) *MockHostOps_Stat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHostOps_Stat_Call) Return(pathInfo machine.PathInfo, err error) *MockHostOps_Stat_Call {
	_c.Call.Return(pathInfo, err)
	return _c
}

func (_c *MockHostOps_Stat_Call) RunAndReturn(run func(path string) (machine.PathInfo, error)) *MockHostOps_Stat_Call {
	_c.Call.Return(run)
	return _c
}

// SubIDRanges provides a mock function for the type MockHostOps
func (_mock *MockHostOps) SubIDRanges(user machine.User) (bool, bool, error) {
	ret := _mock.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for SubIDRanges")
	}

	var r0 bool
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(machine.User) (bool, bool, error)); ok {
		return returnFunc(user)
	}
	if returnFunc, ok := ret.Get(0).(func(machine.User) bool); ok {
		r0 = returnFunc(user)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(machine.User) bool); ok {
		r1 = returnFunc(user)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(machine.User) error); ok {
		r2 = returnFunc(user)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockHostOps_SubIDRanges_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SubIDRanges'
type MockHostOps_SubIDRanges_Call struct {
	*mock.Call
}

// SubIDRanges is a helper method to define mock.On call
//   - user machine.User
func (_e *MockHostOps_Expecter) SubIDRanges(user any) *MockHostOps_SubIDRanges_Call {
	return &MockHostOps_SubIDRanges_Call{Call: _e.mock.On("SubIDRanges", user)}
}

func (_c *MockHostOps_SubIDRanges_Call) Run(run func(user machine.User)) *MockHostOps_SubIDRanges_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 machine.User
		if args[0] != nil {
			arg0 = args[0].(machine.User)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHostOps_SubIDRanges_Call) Return(subuid bool, subgid bool, err error) *MockHostOps_SubIDRanges_Call {
	_c.Call.Return(subuid, subgid, err)
	return _c
}

func (_c *MockHostOps_SubIDRanges_Call) RunAndReturn(run func(user machine.User) (bool, bool, error)) *MockHostOps_SubIDRanges_Call {
	_c.Call.Return(run)
	return _c
}

// SystemUnitEnabled provides a mock function for the type MockHostOps
func (_mock *MockHostOps) SystemUnitEnabled(ctx context.Context, unit string) (bool, error) {
	ret := _mock.Called(ctx, unit)

	if len(ret) == 0 {
		panic("no return value specified for SystemUnitEnabled")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, unit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, unit)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, unit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHostOps_SystemUnitEnabled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SystemUnitEnabled'
type MockHostOps_SystemUnitEnabled_Call struct {
	*mock.Call
}

// SystemUnitEnabled is a helper method to define mock.On call
//   - ctx context.Context
//   - unit string
func (_e *MockHostOps_Expecter) SystemUnitEnabled(ctx any, unit any) *MockHostOps_SystemUnitEnabled_Call {
	return &MockHostOps_SystemUnitEnabled_Call{Call: _e.mock.On("SystemUnitEnabled", ctx, unit)}
}

func (_c *MockHostOps_SystemUnitEnabled_Call) Run(run func(ctx context.Context, unit string)) *MockHostOps_SystemUnitEnabled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHostOps_SystemUnitEnabled_Call) Return(b bool, err error) *MockHostOps_SystemUnitEnabled_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockHostOps_SystemUnitEnabled_Call) RunAndReturn(run func(ctx context.Context, unit string) (bool, error)) *MockHostOps_SystemUnitEnabled_Call {
	_c.Call.Return(run)
	return _c
}

// UserManagerRunning provides a mock function for the type MockHostOps
func (_mock *MockHostOps) UserManagerRunning(user machine.User) (bool, error) {
	ret := _mock.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for UserManagerRunning")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(machine.User) (bool, error)); ok {
		return returnFunc(user)
	}
	if returnFunc, ok := ret.Get(0).(func(machine.User) bool); ok {
		r0 = returnFunc(user)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(machine.User) error); ok {
		r1 = returnFunc(user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHostOps_UserManagerRunning_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserManagerRunning'
type MockHostOps_UserManagerRunning_Call struct {
	*mock.Call
}

// UserManagerRunning is a helper method to define mock.On call
//   - user machine.User
func (_e *MockHostOps_Expecter) UserManagerRunning(user any) *MockHostOps_UserManagerRunning_Call {
	return &MockHostOps_UserManagerRunning_Call{Call: _e.mock.On("UserManagerRunning", user)}
}

func (_c *MockHostOps_UserManagerRunning_Call) Run(run func(user machine.User)) *MockHostOps_UserManagerRunning_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 machine.User
		if args[0] != nil {
			arg0 = args[0].(machine.User)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHostOps_UserManagerRunning_Call) Return(b bool, err error) *MockHostOps_UserManagerRunning_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockHostOps_UserManagerRunning_Call) RunAndReturn(run func(user machine.User) (bool, error)) *MockHostOps_UserManagerRunning_Call {
	_c.Call.Return(run)
	return _c
}

// UserUnitEnabled provides a mock function for the type MockHostOps
func (_mock *MockHostOps) UserUnitEnabled(ctx context.Context, user machine.User, unit string) (bool, error) {
	ret := _mock.Called(ctx, user, unit)

	if len(ret) == 0 {
		panic("no return value specified for UserUnitEnabled")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, machine.User, string) (bool, error)); ok {
		return returnFunc(ctx, user, unit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, machine.User, string) bool); ok {
		r0 = returnFunc(ctx, user, unit)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, machine.User, string) error); ok {
		r1 = returnFunc(ctx, user, unit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHostOps_UserUnitEnabled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserUnitEnabled'
type MockHostOps_UserUnitEnabled_Call struct {
	*mock.Call
}

// UserUnitEnabled is a helper method to define mock.On call
//   - ctx context.Context
//   - user machine.User
//   - unit string
func (_e *MockHostOps_Expecter) UserUnitEnabled(ctx any, user any, unit any) *MockHostOps_UserUnitEnabled_Call {
	return &MockHostOps_UserUnitEnabled_Call{Call: _e.mock.On("UserUnitEnabled", ctx, user, unit)}
}

func (_c *MockHostOps_UserUnitEnabled_Call) Run(run func(ctx context.Context, user machine.User, unit string)) *MockHostOps_UserUnitEnabled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 machine.User
		if args[1] != nil {
			arg1 = args[1].(machine.User)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockHostOps_UserUnitEnabled_Call) Return(b bool, err error) *MockHostOps_UserUnitEnabled_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockHostOps_UserUnitEnabled_Call) RunAndReturn(run func(ctx context.Context, user machine.User, unit string) (bool, error)) *MockHostOps_UserUnitEnabled_Call {
	_c.Call.Return(run)
	return _c
}

// WorldReadableTree provides a mock function for the type MockHostOps
func (_mock *MockHostOps) WorldReadableTree(path string) (bool, error) {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for WorldReadableTree")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (bool, error)); ok {
		return returnFunc(path)
	}
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(path)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHostOps_WorldReadableTree_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WorldReadableTree'
type MockHostOps_WorldReadableTree_Call struct {
	*mock.Call
}

// WorldReadableTree is a helper method to define mock.On call
//   - path string
func (_e *MockHostOps_Expecter) WorldReadableTree(path any) *MockHostOps_WorldReadableTree_Call {
	return &MockHostOps_WorldReadableTree_Call{Call: _e.mock.On("WorldReadableTree", path)}
}

func (_c *MockHostOps_WorldReadableTree_Call) Run(run func(path string)) *MockHostOps_WorldReadableTree_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHostOps_WorldReadableTree_Call) Return(b bool, err error) *MockHostOps_WorldReadableTree_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockHostOps_WorldReadableTree_Call) RunAndReturn(run func(path string) (bool, error)) *MockHostOps_WorldReadableTree_Call {
	_c.Call.Return(run)
	return _c
}
