// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/schjan/picolet/pkg/applier"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSystemdManager creates a new instance of MockSystemdManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSystemdManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSystemdManager {
	mock := &MockSystemdManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSystemdManager is an autogenerated mock type for the SystemdManager type
type MockSystemdManager struct {
	mock.Mock
}

type MockSystemdManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSystemdManager) EXPECT() *MockSystemdManager_Expecter {
	return &MockSystemdManager_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockSystemdManager
func (_mock *MockSystemdManager) Close() {
	_mock.Called()
	return
}

// MockSystemdManager_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockSystemdManager_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockSystemdManager_Expecter) Close() *MockSystemdManager_Close_Call {
	return &MockSystemdManager_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockSystemdManager_Close_Call) Run(run func()) *MockSystemdManager_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSystemdManager_Close_Call) Return() *MockSystemdManager_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSystemdManager_Close_Call) RunAndReturn(run func()) *MockSystemdManager_Close_Call {
	_c.Run(run)
	return _c
}

// DaemonReload provides a mock function for the type MockSystemdManager
func (_mock *MockSystemdManager) DaemonReload(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for DaemonReload")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSystemdManager_DaemonReload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DaemonReload'
type MockSystemdManager_DaemonReload_Call struct {
	*mock.Call
}

// DaemonReload is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSystemdManager_Expecter) DaemonReload(ctx any) *MockSystemdManager_DaemonReload_Call {
	return &MockSystemdManager_DaemonReload_Call{Call: _e.mock.On("DaemonReload", ctx)}
}

func (_c *MockSystemdManager_DaemonReload_Call) Run(run func(ctx context.Context)) *MockSystemdManager_DaemonReload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSystemdManager_DaemonReload_Call) Return(err error) *MockSystemdManager_DaemonReload_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSystemdManager_DaemonReload_Call) RunAndReturn(run func(ctx context.Context) error) *MockSystemdManager_DaemonReload_Call {
	_c.Call.Return(run)
	return _c
}

// DisableUnit provides a mock function for the type MockSystemdManager
func (_mock *MockSystemdManager) DisableUnit(ctx context.Context, name string) error {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for DisableUnit")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSystemdManager_DisableUnit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DisableUnit'
type MockSystemdManager_DisableUnit_Call struct {
	*mock.Call
}

// DisableUnit is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockSystemdManager_Expecter) DisableUnit(ctx any, name any) *MockSystemdManager_DisableUnit_Call {
	return &MockSystemdManager_DisableUnit_Call{Call: _e.mock.On("DisableUnit", ctx, name)}
}

func (_c *MockSystemdManager_DisableUnit_Call) Run(run func(ctx context.Context, name string)) *MockSystemdManager_DisableUnit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSystemdManager_DisableUnit_Call) Return(err error) *MockSystemdManager_DisableUnit_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSystemdManager_DisableUnit_Call) RunAndReturn(run func(ctx context.Context, name string) error) *MockSystemdManager_DisableUnit_Call {
	_c.Call.Return(run)
	return _c
}

// EnableUnit provides a mock function for the type MockSystemdManager
func (_mock *MockSystemdManager) EnableUnit(ctx context.Context, name string) error {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for EnableUnit")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSystemdManager_EnableUnit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnableUnit'
type MockSystemdManager_EnableUnit_Call struct {
	*mock.Call
}

// EnableUnit is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockSystemdManager_Expecter) EnableUnit(ctx any, name any) *MockSystemdManager_EnableUnit_Call {
	return &MockSystemdManager_EnableUnit_Call{Call: _e.mock.On("EnableUnit", ctx, name)}
}

func (_c *MockSystemdManager_EnableUnit_Call) Run(run func(ctx context.Context, name string)) *MockSystemdManager_EnableUnit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSystemdManager_EnableUnit_Call) Return(err error) *MockSystemdManager_EnableUnit_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSystemdManager_EnableUnit_Call) RunAndReturn(run func(ctx context.Context, name string) error) *MockSystemdManager_EnableUnit_Call {
	_c.Call.Return(run)
	return _c
}

// GetUnitStatus provides a mock function for the type MockSystemdManager
func (_mock *MockSystemdManager) GetUnitStatus(ctx context.Context, name string) (applier.UnitStatus, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetUnitStatus")
	}

	var r0 applier.UnitStatus
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (applier.UnitStatus, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) applier.UnitStatus); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Get(0).(applier.UnitStatus)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSystemdManager_GetUnitStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUnitStatus'
type MockSystemdManager_GetUnitStatus_Call struct {
	*mock.Call
}

// GetUnitStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockSystemdManager_Expecter) GetUnitStatus(ctx any, name any) *MockSystemdManager_GetUnitStatus_Call {
	return &MockSystemdManager_GetUnitStatus_Call{Call: _e.mock.On("GetUnitStatus", ctx, name)}
}

func (_c *MockSystemdManager_GetUnitStatus_Call) Run(run func(ctx context.Context, name string)) *MockSystemdManager_GetUnitStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSystemdManager_GetUnitStatus_Call) Return(unitStatus applier.UnitStatus, err error) *MockSystemdManager_GetUnitStatus_Call {
	_c.Call.Return(unitStatus, err)
	return _c
}

func (_c *MockSystemdManager_GetUnitStatus_Call) RunAndReturn(run func(ctx context.Context, name string) (applier.UnitStatus, error)) *MockSystemdManager_GetUnitStatus_Call {
	_c.Call.Return(run)
	return _c
}

// RestartUnit provides a mock function for the type MockSystemdManager
func (_mock *MockSystemdManager) RestartUnit(ctx context.Context, name string) error {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for RestartUnit")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSystemdManager_RestartUnit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RestartUnit'
type MockSystemdManager_RestartUnit_Call struct {
	*mock.Call
}

// RestartUnit is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockSystemdManager_Expecter) RestartUnit(ctx any, name any) *MockSystemdManager_RestartUnit_Call {
	return &MockSystemdManager_RestartUnit_Call{Call: _e.mock.On("RestartUnit", ctx, name)}
}

func (_c *MockSystemdManager_RestartUnit_Call) Run(run func(ctx context.Context, name string)) *MockSystemdManager_RestartUnit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSystemdManager_RestartUnit_Call) Return(err error) *MockSystemdManager_RestartUnit_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSystemdManager_RestartUnit_Call) RunAndReturn(run func(ctx context.Context, name string) error) *MockSystemdManager_RestartUnit_Call {
	_c.Call.Return(run)
	return _c
}

// StartUnit provides a mock function for the type MockSystemdManager
func (_mock *MockSystemdManager) StartUnit(ctx context.Context, name string) error {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for StartUnit")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSystemdManager_StartUnit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartUnit'
type MockSystemdManager_StartUnit_Call struct {
	*mock.Call
}

// StartUnit is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockSystemdManager_Expecter) StartUnit(ctx any, name any) *MockSystemdManager_StartUnit_Call {
	return &MockSystemdManager_StartUnit_Call{Call: _e.mock.On("StartUnit", ctx, name)}
}

func (_c *MockSystemdManager_StartUnit_Call) Run(run func(ctx context.Context, name string)) *MockSystemdManager_StartUnit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSystemdManager_StartUnit_Call) Return(err error) *MockSystemdManager_StartUnit_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSystemdManager_StartUnit_Call) RunAndReturn(run func(ctx context.Context, name string) error) *MockSystemdManager_StartUnit_Call {
	_c.Call.Return(run)
	return _c
}

// StopUnit provides a mock function for the type MockSystemdManager
func (_mock *MockSystemdManager) StopUnit(ctx context.Context, name string) error {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for StopUnit")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSystemdManager_StopUnit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StopUnit'
type MockSystemdManager_StopUnit_Call struct {
	*mock.Call
}

// StopUnit is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockSystemdManager_Expecter) StopUnit(ctx any, name any) *MockSystemdManager_StopUnit_Call {
	return &MockSystemdManager_StopUnit_Call{Call: _e.mock.On("StopUnit", ctx, name)}
}

func (_c *MockSystemdManager_StopUnit_Call) Run(run func(ctx context.Context, name string)) *MockSystemdManager_StopUnit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSystemdManager_StopUnit_Call) Return(err error) *MockSystemdManager_StopUnit_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSystemdManager_StopUnit_Call) RunAndReturn(run func(ctx context.Context, name string) error) *MockSystemdManager_StopUnit_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPodmanClient creates a new instance of MockPodmanClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPodmanClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPodmanClient {
	mock := &MockPodmanClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPodmanClient is an autogenerated mock type for the PodmanClient type
type MockPodmanClient struct {
	mock.Mock
}

type MockPodmanClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPodmanClient) EXPECT() *MockPodmanClient_Expecter {
	return &MockPodmanClient_Expecter{mock: &_m.Mock}
}

// ContainerKill provides a mock function for the type MockPodmanClient
func (_mock *MockPodmanClient) ContainerKill(ctx context.Context, nameOrID string, signal string) error {
	ret := _mock.Called(ctx, nameOrID, signal)

	if len(ret) == 0 {
		panic("no return value specified for ContainerKill")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, nameOrID, signal)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPodmanClient_ContainerKill_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContainerKill'
type MockPodmanClient_ContainerKill_Call struct {
	*mock.Call
}

// ContainerKill is a helper method to define mock.On call
//   - ctx context.Context
//   - nameOrID string
//   - signal string
func (_e *MockPodmanClient_Expecter) ContainerKill(ctx any, nameOrID any, signal any) *MockPodmanClient_ContainerKill_Call {
	return &MockPodmanClient_ContainerKill_Call{Call: _e.mock.On("ContainerKill", ctx, nameOrID, signal)}
}

func (_c *MockPodmanClient_ContainerKill_Call) Run(run func(ctx context.Context, nameOrID string, signal string)) *MockPodmanClient_ContainerKill_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPodmanClient_ContainerKill_Call) Return(err error) *MockPodmanClient_ContainerKill_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPodmanClient_ContainerKill_Call) RunAndReturn(run func(ctx context.Context, nameOrID string, signal string) error) *MockPodmanClient_ContainerKill_Call {
	_c.Call.Return(run)
	return _c
}

// ImagePrune provides a mock function for the type MockPodmanClient
func (_mock *MockPodmanClient) ImagePrune(ctx context.Context, all bool) (applier.PruneResult, error) {
	ret := _mock.Called(ctx, all)

	if len(ret) == 0 {
		panic("no return value specified for ImagePrune")
	}

	var r0 applier.PruneResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, bool) (applier.PruneResult, error)); ok {
		return returnFunc(ctx, all)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, bool) applier.PruneResult); ok {
		r0 = returnFunc(ctx, all)
	} else {
		r0 = ret.Get(0).(applier.PruneResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, bool) error); ok {
		r1 = returnFunc(ctx, all)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPodmanClient_ImagePrune_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ImagePrune'
type MockPodmanClient_ImagePrune_Call struct {
	*mock.Call
}

// ImagePrune is a helper method to define mock.On call
//   - ctx context.Context
//   - all bool
func (_e *MockPodmanClient_Expecter) ImagePrune(ctx any, all any) *MockPodmanClient_ImagePrune_Call {
	return &MockPodmanClient_ImagePrune_Call{Call: _e.mock.On("ImagePrune", ctx, all)}
}

func (_c *MockPodmanClient_ImagePrune_Call) Run(run func(ctx context.Context, all bool)) *MockPodmanClient_ImagePrune_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 bool
		if args[1] != nil {
			arg1 = args[1].(bool)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPodmanClient_ImagePrune_Call) Return(pruneResult applier.PruneResult, err error) *MockPodmanClient_ImagePrune_Call {
	_c.Call.Return(pruneResult, err)
	return _c
}

func (_c *MockPodmanClient_ImagePrune_Call) RunAndReturn(run func(ctx context.Context, all bool) (applier.PruneResult, error)) *MockPodmanClient_ImagePrune_Call {
	_c.Call.Return(run)
	return _c
}

// ListManagedSecrets provides a mock function for the type MockPodmanClient
func (_mock *MockPodmanClient) ListManagedSecrets(ctx context.Context) ([]string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListManagedSecrets")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPodmanClient_ListManagedSecrets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListManagedSecrets'
type MockPodmanClient_ListManagedSecrets_Call struct {
	*mock.Call
}

// ListManagedSecrets is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockPodmanClient_Expecter) ListManagedSecrets(ctx any) *MockPodmanClient_ListManagedSecrets_Call {
	return &MockPodmanClient_ListManagedSecrets_Call{Call: _e.mock.On("ListManagedSecrets", ctx)}
}

func (_c *MockPodmanClient_ListManagedSecrets_Call) Run(run func(ctx context.Context)) *MockPodmanClient_ListManagedSecrets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPodmanClient_ListManagedSecrets_Call) Return(strings []string, err error) *MockPodmanClient_ListManagedSecrets_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockPodmanClient_ListManagedSecrets_Call) RunAndReturn(run func(ctx context.Context) ([]string, error)) *MockPodmanClient_ListManagedSecrets_Call {
	_c.Call.Return(run)
	return _c
}

// SecretCreate provides a mock function for the type MockPodmanClient
func (_mock *MockPodmanClient) SecretCreate(ctx context.Context, name string, data []byte, replace bool) error {
	ret := _mock.Called(ctx, name, data, replace)

	if len(ret) == 0 {
		panic("no return value specified for SecretCreate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []byte, bool) error); ok {
		r0 = returnFunc(ctx, name, data, replace)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPodmanClient_SecretCreate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SecretCreate'
type MockPodmanClient_SecretCreate_Call struct {
	*mock.Call
}

// SecretCreate is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - data []byte
//   - replace bool
func (_e *MockPodmanClient_Expecter) SecretCreate(ctx any, name any, data any, replace any) *MockPodmanClient_SecretCreate_Call {
	return &MockPodmanClient_SecretCreate_Call{Call: _e.mock.On("SecretCreate", ctx, name, data, replace)}
}

func (_c *MockPodmanClient_SecretCreate_Call) Run(run func(ctx context.Context, name string, data []byte, replace bool)) *MockPodmanClient_SecretCreate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockPodmanClient_SecretCreate_Call) Return(err error) *MockPodmanClient_SecretCreate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPodmanClient_SecretCreate_Call) RunAndReturn(run func(ctx context.Context, name string, data []byte, replace bool) error) *MockPodmanClient_SecretCreate_Call {
	_c.Call.Return(run)
	return _c
}

// SecretRemove provides a mock function for the type MockPodmanClient
func (_mock *MockPodmanClient) SecretRemove(ctx context.Context, name string) error {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for SecretRemove")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPodmanClient_SecretRemove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SecretRemove'
type MockPodmanClient_SecretRemove_Call struct {
	*mock.Call
}

// SecretRemove is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockPodmanClient_Expecter) SecretRemove(ctx any, name any) *MockPodmanClient_SecretRemove_Call {
	return &MockPodmanClient_SecretRemove_Call{Call: _e.mock.On("SecretRemove", ctx, name)}
}

func (_c *MockPodmanClient_SecretRemove_Call) Run(run func(ctx context.Context, name string)) *MockPodmanClient_SecretRemove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPodmanClient_SecretRemove_Call) Return(err error) *MockPodmanClient_SecretRemove_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPodmanClient_SecretRemove_Call) RunAndReturn(run func(ctx context.Context, name string) error) *MockPodmanClient_SecretRemove_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFileWriter creates a new instance of MockFileWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFileWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFileWriter {
	mock := &MockFileWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFileWriter is an autogenerated mock type for the FileWriter type
type MockFileWriter struct {
	mock.Mock
}

type MockFileWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFileWriter) EXPECT() *MockFileWriter_Expecter {
	return &MockFileWriter_Expecter{mock: &_m.Mock}
}

// MkdirAll provides a mock function for the type MockFileWriter
func (_mock *MockFileWriter) MkdirAll(path string) error {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for MkdirAll")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(path)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFileWriter_MkdirAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MkdirAll'
type MockFileWriter_MkdirAll_Call struct {
	*mock.Call
}

// MkdirAll is a helper method to define mock.On call
//   - path string
func (_e *MockFileWriter_Expecter) MkdirAll(path any) *MockFileWriter_MkdirAll_Call {
	return &MockFileWriter_MkdirAll_Call{Call: _e.mock.On("MkdirAll", path)}
}

func (_c *MockFileWriter_MkdirAll_Call) Run(run func(path string)) *MockFileWriter_MkdirAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFileWriter_MkdirAll_Call) Return(err error) *MockFileWriter_MkdirAll_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFileWriter_MkdirAll_Call) RunAndReturn(run func(path string) error) *MockFileWriter_MkdirAll_Call {
	_c.Call.Return(run)
	return _c
}

// Remove provides a mock function for the type MockFileWriter
func (_mock *MockFileWriter) Remove(path string) error {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(path)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFileWriter_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type MockFileWriter_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - path string
func (_e *MockFileWriter_Expecter) Remove(path any) *MockFileWriter_Remove_Call {
	return &MockFileWriter_Remove_Call{Call: _e.mock.On("Remove", path)}
}

func (_c *MockFileWriter_Remove_Call) Run(run func(path string)) *MockFileWriter_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFileWriter_Remove_Call) Return(err error) *MockFileWriter_Remove_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFileWriter_Remove_Call) RunAndReturn(run func(path string) error) *MockFileWriter_Remove_Call {
	_c.Call.Return(run)
	return _c
}

// WriteFile provides a mock function for the type MockFileWriter
func (_mock *MockFileWriter) WriteFile(path string, content []byte) error {
	ret := _mock.Called(path, content)

	if len(ret) == 0 {
		panic("no return value specified for WriteFile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, []byte) error); ok {
		r0 = returnFunc(path, content)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFileWriter_WriteFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteFile'
type MockFileWriter_WriteFile_Call struct {
	*mock.Call
}

// WriteFile is a helper method to define mock.On call
//   - path string
//   - content []byte
func (_e *MockFileWriter_Expecter) WriteFile(path any, content any) *MockFileWriter_WriteFile_Call {
	return &MockFileWriter_WriteFile_Call{Call: _e.mock.On("WriteFile", path, content)}
}

func (_c *MockFileWriter_WriteFile_Call) Run(run func(path string, content []byte)) *MockFileWriter_WriteFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileWriter_WriteFile_Call) Return(err error) *MockFileWriter_WriteFile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFileWriter_WriteFile_Call) RunAndReturn(run func(path string, content []byte) error) *MockFileWriter_WriteFile_Call {
	_c.Call.Return(run)
	return _c
}
