// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockSystemdManager creates a new instance of MockSystemdManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSystemdManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSystemdManager {
	mock := &MockSystemdManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSystemdManager is an autogenerated mock type for the SystemdManager type
type MockSystemdManager struct {
	mock.Mock
}

type MockSystemdManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSystemdManager) EXPECT() *MockSystemdManager_Expecter {
	return &MockSystemdManager_Expecter{mock: &_m.Mock}
}

// DaemonReload provides a mock function for the type MockSystemdManager
func (_mock *MockSystemdManager) DaemonReload(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for DaemonReload")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSystemdManager_DaemonReload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DaemonReload'
type MockSystemdManager_DaemonReload_Call struct {
	*mock.Call
}

// DaemonReload is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSystemdManager_Expecter) DaemonReload(ctx interface{}) *MockSystemdManager_DaemonReload_Call {
	return &MockSystemdManager_DaemonReload_Call{Call: _e.mock.On("DaemonReload", ctx)}
}

func (_c *MockSystemdManager_DaemonReload_Call) Run(run func(ctx context.Context)) *MockSystemdManager_DaemonReload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSystemdManager_DaemonReload_Call) Return(err error) *MockSystemdManager_DaemonReload_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSystemdManager_DaemonReload_Call) RunAndReturn(run func(ctx context.Context) error) *MockSystemdManager_DaemonReload_Call {
	_c.Call.Return(run)
	return _c
}

// GetUnitState provides a mock function for the type MockSystemdManager
func (_mock *MockSystemdManager) GetUnitState(ctx context.Context, name string) (string, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetUnitState")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSystemdManager_GetUnitState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUnitState'
type MockSystemdManager_GetUnitState_Call struct {
	*mock.Call
}

// GetUnitState is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockSystemdManager_Expecter) GetUnitState(ctx interface{}, name interface{}) *MockSystemdManager_GetUnitState_Call {
	return &MockSystemdManager_GetUnitState_Call{Call: _e.mock.On("GetUnitState", ctx, name)}
}

func (_c *MockSystemdManager_GetUnitState_Call) Run(run func(ctx context.Context, name string)) *MockSystemdManager_GetUnitState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSystemdManager_GetUnitState_Call) Return(s string, err error) *MockSystemdManager_GetUnitState_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockSystemdManager_GetUnitState_Call) RunAndReturn(run func(ctx context.Context, name string) (string, error)) *MockSystemdManager_GetUnitState_Call {
	_c.Call.Return(run)
	return _c
}

// IsActive provides a mock function for the type MockSystemdManager
func (_mock *MockSystemdManager) IsActive(ctx context.Context, name string) (bool, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for IsActive")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSystemdManager_IsActive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsActive'
type MockSystemdManager_IsActive_Call struct {
	*mock.Call
}

// IsActive is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockSystemdManager_Expecter) IsActive(ctx interface{}, name interface{}) *MockSystemdManager_IsActive_Call {
	return &MockSystemdManager_IsActive_Call{Call: _e.mock.On("IsActive", ctx, name)}
}

func (_c *MockSystemdManager_IsActive_Call) Run(run func(ctx context.Context, name string)) *MockSystemdManager_IsActive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSystemdManager_IsActive_Call) Return(b bool, err error) *MockSystemdManager_IsActive_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockSystemdManager_IsActive_Call) RunAndReturn(run func(ctx context.Context, name string) (bool, error)) *MockSystemdManager_IsActive_Call {
	_c.Call.Return(run)
	return _c
}

// RestartUnit provides a mock function for the type MockSystemdManager
func (_mock *MockSystemdManager) RestartUnit(ctx context.Context, name string) error {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for RestartUnit")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSystemdManager_RestartUnit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RestartUnit'
type MockSystemdManager_RestartUnit_Call struct {
	*mock.Call
}

// RestartUnit is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockSystemdManager_Expecter) RestartUnit(ctx interface{}, name interface{}) *MockSystemdManager_RestartUnit_Call {
	return &MockSystemdManager_RestartUnit_Call{Call: _e.mock.On("RestartUnit", ctx, name)}
}

func (_c *MockSystemdManager_RestartUnit_Call) Run(run func(ctx context.Context, name string)) *MockSystemdManager_RestartUnit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSystemdManager_RestartUnit_Call) Return(err error) *MockSystemdManager_RestartUnit_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSystemdManager_RestartUnit_Call) RunAndReturn(run func(ctx context.Context, name string) error) *MockSystemdManager_RestartUnit_Call {
	_c.Call.Return(run)
	return _c
}

// StartUnit provides a mock function for the type MockSystemdManager
func (_mock *MockSystemdManager) StartUnit(ctx context.Context, name string) error {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for StartUnit")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSystemdManager_StartUnit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartUnit'
type MockSystemdManager_StartUnit_Call struct {
	*mock.Call
}

// StartUnit is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockSystemdManager_Expecter) StartUnit(ctx interface{}, name interface{}) *MockSystemdManager_StartUnit_Call {
	return &MockSystemdManager_StartUnit_Call{Call: _e.mock.On("StartUnit", ctx, name)}
}

func (_c *MockSystemdManager_StartUnit_Call) Run(run func(ctx context.Context, name string)) *MockSystemdManager_StartUnit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSystemdManager_StartUnit_Call) Return(err error) *MockSystemdManager_StartUnit_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSystemdManager_StartUnit_Call) RunAndReturn(run func(ctx context.Context, name string) error) *MockSystemdManager_StartUnit_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPodmanClient creates a new instance of MockPodmanClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPodmanClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPodmanClient {
	mock := &MockPodmanClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPodmanClient is an autogenerated mock type for the PodmanClient type
type MockPodmanClient struct {
	mock.Mock
}

type MockPodmanClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPodmanClient) EXPECT() *MockPodmanClient_Expecter {
	return &MockPodmanClient_Expecter{mock: &_m.Mock}
}

// ContainerRemove provides a mock function for the type MockPodmanClient
func (_mock *MockPodmanClient) ContainerRemove(ctx context.Context, nameOrID string, force bool) error {
	ret := _mock.Called(ctx, nameOrID, force)

	if len(ret) == 0 {
		panic("no return value specified for ContainerRemove")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bool) error); ok {
		r0 = returnFunc(ctx, nameOrID, force)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPodmanClient_ContainerRemove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContainerRemove'
type MockPodmanClient_ContainerRemove_Call struct {
	*mock.Call
}

// ContainerRemove is a helper method to define mock.On call
//   - ctx context.Context
//   - nameOrID string
//   - force bool
func (_e *MockPodmanClient_Expecter) ContainerRemove(ctx interface{}, nameOrID interface{}, force interface{}) *MockPodmanClient_ContainerRemove_Call {
	return &MockPodmanClient_ContainerRemove_Call{Call: _e.mock.On("ContainerRemove", ctx, nameOrID, force)}
}

func (_c *MockPodmanClient_ContainerRemove_Call) Run(run func(ctx context.Context, nameOrID string, force bool)) *MockPodmanClient_ContainerRemove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPodmanClient_ContainerRemove_Call) Return(err error) *MockPodmanClient_ContainerRemove_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPodmanClient_ContainerRemove_Call) RunAndReturn(run func(ctx context.Context, nameOrID string, force bool) error) *MockPodmanClient_ContainerRemove_Call {
	_c.Call.Return(run)
	return _c
}

// GetPodState provides a mock function for the type MockPodmanClient
func (_mock *MockPodmanClient) GetPodState(ctx context.Context, pod string) (string, error) {
	ret := _mock.Called(ctx, pod)

	if len(ret) == 0 {
		panic("no return value specified for GetPodState")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, pod)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, pod)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, pod)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPodmanClient_GetPodState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPodState'
type MockPodmanClient_GetPodState_Call struct {
	*mock.Call
}

// GetPodState is a helper method to define mock.On call
//   - ctx context.Context
//   - pod string
func (_e *MockPodmanClient_Expecter) GetPodState(ctx interface{}, pod interface{}) *MockPodmanClient_GetPodState_Call {
	return &MockPodmanClient_GetPodState_Call{Call: _e.mock.On("GetPodState", ctx, pod)}
}

func (_c *MockPodmanClient_GetPodState_Call) Run(run func(ctx context.Context, pod string)) *MockPodmanClient_GetPodState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPodmanClient_GetPodState_Call) Return(s string, err error) *MockPodmanClient_GetPodState_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockPodmanClient_GetPodState_Call) RunAndReturn(run func(ctx context.Context, pod string) (string, error)) *MockPodmanClient_GetPodState_Call {
	_c.Call.Return(run)
	return _c
}

// RunHealthcheck provides a mock function for the type MockPodmanClient
func (_mock *MockPodmanClient) RunHealthcheck(ctx context.Context, container string) (bool, error) {
	ret := _mock.Called(ctx, container)

	if len(ret) == 0 {
		panic("no return value specified for RunHealthcheck")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, container)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, container)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, container)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPodmanClient_RunHealthcheck_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunHealthcheck'
type MockPodmanClient_RunHealthcheck_Call struct {
	*mock.Call
}

// RunHealthcheck is a helper method to define mock.On call
//   - ctx context.Context
//   - container string
func (_e *MockPodmanClient_Expecter) RunHealthcheck(ctx interface{}, container interface{}) *MockPodmanClient_RunHealthcheck_Call {
	return &MockPodmanClient_RunHealthcheck_Call{Call: _e.mock.On("RunHealthcheck", ctx, container)}
}

func (_c *MockPodmanClient_RunHealthcheck_Call) Run(run func(ctx context.Context, container string)) *MockPodmanClient_RunHealthcheck_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPodmanClient_RunHealthcheck_Call) Return(b bool, err error) *MockPodmanClient_RunHealthcheck_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockPodmanClient_RunHealthcheck_Call) RunAndReturn(run func(ctx context.Context, container string) (bool, error)) *MockPodmanClient_RunHealthcheck_Call {
	_c.Call.Return(run)
	return _c
}

// SecretCreate provides a mock function for the type MockPodmanClient
func (_mock *MockPodmanClient) SecretCreate(ctx context.Context, name string, data []byte, replace bool) error {
	ret := _mock.Called(ctx, name, data, replace)

	if len(ret) == 0 {
		panic("no return value specified for SecretCreate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []byte, bool) error); ok {
		r0 = returnFunc(ctx, name, data, replace)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPodmanClient_SecretCreate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SecretCreate'
type MockPodmanClient_SecretCreate_Call struct {
	*mock.Call
}

// SecretCreate is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - data []byte
//   - replace bool
func (_e *MockPodmanClient_Expecter) SecretCreate(ctx interface{}, name interface{}, data interface{}, replace interface{}) *MockPodmanClient_SecretCreate_Call {
	return &MockPodmanClient_SecretCreate_Call{Call: _e.mock.On("SecretCreate", ctx, name, data, replace)}
}

func (_c *MockPodmanClient_SecretCreate_Call) Run(run func(ctx context.Context, name string, data []byte, replace bool)) *MockPodmanClient_SecretCreate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockPodmanClient_SecretCreate_Call) Return(err error) *MockPodmanClient_SecretCreate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPodmanClient_SecretCreate_Call) RunAndReturn(run func(ctx context.Context, name string, data []byte, replace bool) error) *MockPodmanClient_SecretCreate_Call {
	_c.Call.Return(run)
	return _c
}

// SecretExists provides a mock function for the type MockPodmanClient
func (_mock *MockPodmanClient) SecretExists(ctx context.Context, name string) (bool, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for SecretExists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPodmanClient_SecretExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SecretExists'
type MockPodmanClient_SecretExists_Call struct {
	*mock.Call
}

// SecretExists is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockPodmanClient_Expecter) SecretExists(ctx interface{}, name interface{}) *MockPodmanClient_SecretExists_Call {
	return &MockPodmanClient_SecretExists_Call{Call: _e.mock.On("SecretExists", ctx, name)}
}

func (_c *MockPodmanClient_SecretExists_Call) Run(run func(ctx context.Context, name string)) *MockPodmanClient_SecretExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPodmanClient_SecretExists_Call) Return(b bool, err error) *MockPodmanClient_SecretExists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockPodmanClient_SecretExists_Call) RunAndReturn(run func(ctx context.Context, name string) (bool, error)) *MockPodmanClient_SecretExists_Call {
	_c.Call.Return(run)
	return _c
}

// SecretRemove provides a mock function for the type MockPodmanClient
func (_mock *MockPodmanClient) SecretRemove(ctx context.Context, name string) error {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for SecretRemove")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPodmanClient_SecretRemove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SecretRemove'
type MockPodmanClient_SecretRemove_Call struct {
	*mock.Call
}

// SecretRemove is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockPodmanClient_Expecter) SecretRemove(ctx interface{}, name interface{}) *MockPodmanClient_SecretRemove_Call {
	return &MockPodmanClient_SecretRemove_Call{Call: _e.mock.On("SecretRemove", ctx, name)}
}

func (_c *MockPodmanClient_SecretRemove_Call) Run(run func(ctx context.Context, name string)) *MockPodmanClient_SecretRemove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPodmanClient_SecretRemove_Call) Return(err error) *MockPodmanClient_SecretRemove_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPodmanClient_SecretRemove_Call) RunAndReturn(run func(ctx context.Context, name string) error) *MockPodmanClient_SecretRemove_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFileWriter creates a new instance of MockFileWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFileWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFileWriter {
	mock := &MockFileWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFileWriter is an autogenerated mock type for the FileWriter type
type MockFileWriter struct {
	mock.Mock
}

type MockFileWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFileWriter) EXPECT() *MockFileWriter_Expecter {
	return &MockFileWriter_Expecter{mock: &_m.Mock}
}

// MkdirAll provides a mock function for the type MockFileWriter
func (_mock *MockFileWriter) MkdirAll(path string) error {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for MkdirAll")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(path)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFileWriter_MkdirAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MkdirAll'
type MockFileWriter_MkdirAll_Call struct {
	*mock.Call
}

// MkdirAll is a helper method to define mock.On call
//   - path string
func (_e *MockFileWriter_Expecter) MkdirAll(path interface{}) *MockFileWriter_MkdirAll_Call {
	return &MockFileWriter_MkdirAll_Call{Call: _e.mock.On("MkdirAll", path)}
}

func (_c *MockFileWriter_MkdirAll_Call) Run(run func(path string)) *MockFileWriter_MkdirAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFileWriter_MkdirAll_Call) Return(err error) *MockFileWriter_MkdirAll_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFileWriter_MkdirAll_Call) RunAndReturn(run func(path string) error) *MockFileWriter_MkdirAll_Call {
	_c.Call.Return(run)
	return _c
}

// Remove provides a mock function for the type MockFileWriter
func (_mock *MockFileWriter) Remove(path string) error {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(path)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFileWriter_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type MockFileWriter_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - path string
func (_e *MockFileWriter_Expecter) Remove(path interface{}) *MockFileWriter_Remove_Call {
	return &MockFileWriter_Remove_Call{Call: _e.mock.On("Remove", path)}
}

func (_c *MockFileWriter_Remove_Call) Run(run func(path string)) *MockFileWriter_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFileWriter_Remove_Call) Return(err error) *MockFileWriter_Remove_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFileWriter_Remove_Call) RunAndReturn(run func(path string) error) *MockFileWriter_Remove_Call {
	_c.Call.Return(run)
	return _c
}

// WriteFile provides a mock function for the type MockFileWriter
func (_mock *MockFileWriter) WriteFile(path string, content []byte) error {
	ret := _mock.Called(path, content)

	if len(ret) == 0 {
		panic("no return value specified for WriteFile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, []byte) error); ok {
		r0 = returnFunc(path, content)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFileWriter_WriteFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteFile'
type MockFileWriter_WriteFile_Call struct {
	*mock.Call
}

// WriteFile is a helper method to define mock.On call
//   - path string
//   - content []byte
func (_e *MockFileWriter_Expecter) WriteFile(path interface{}, content interface{}) *MockFileWriter_WriteFile_Call {
	return &MockFileWriter_WriteFile_Call{Call: _e.mock.On("WriteFile", path, content)}
}

func (_c *MockFileWriter_WriteFile_Call) Run(run func(path string, content []byte)) *MockFileWriter_WriteFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileWriter_WriteFile_Call) Return(err error) *MockFileWriter_WriteFile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFileWriter_WriteFile_Call) RunAndReturn(run func(path string, content []byte) error) *MockFileWriter_WriteFile_Call {
	_c.Call.Return(run)
	return _c
}
